version: '3.4'

services:
  postgresDb:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=GradeDb
    ports:
      - "5438:5432"
    volumes:
      - postgres_val:/home/app/lib/postgres